trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  pythonVersion: '3.13'

stages:

# ============================================================
# BUILD + SONARQUBE + TRIVY + DOCKER + ACR
# ============================================================

- stage: Build
  displayName: Build and Security

  jobs:
  - job: Build
    displayName: Build Application

    steps:

    # --------------------------------------------------------
    # Python
    # --------------------------------------------------------

    - task: UsePythonVersion@0
      displayName: Use Python $(pythonVersion)
      inputs:
        versionSpec: '$(pythonVersion)'

    - script: |
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: Install Python Dependencies

    # --------------------------------------------------------
    # Application validation
    # --------------------------------------------------------

    - script: |
        python -m py_compile app.py
      displayName: Python Syntax Check

    # --------------------------------------------------------
    # SonarQube
    # --------------------------------------------------------

    - script: |
        echo "Installing SonarScanner..."

        SONAR_VERSION="7.2.0.5079"

        wget -q \
          "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux-x64.zip"

        unzip -q \
          "sonar-scanner-cli-${SONAR_VERSION}-linux-x64.zip"

        export PATH="$PWD/sonar-scanner-${SONAR_VERSION}-linux-x64/bin:$PATH"

        sonar-scanner \
          -Dsonar.projectKey=Employee-Management \
          -Dsonar.projectName=Employee-Management \
          -Dsonar.sources=app.py,templates \
          -Dsonar.exclusions=venv/**,**/__pycache__/** \
          -Dsonar.host.url="$SONAR_HOST_URL" \
          -Dsonar.token="$SONAR_TOKEN"
      displayName: SonarQube Analysis
      env:
        SONAR_HOST_URL: http://20.124.249.106:9000
        SONAR_TOKEN: $(SONAR_TOKEN)

    # --------------------------------------------------------
    # Trivy filesystem scan
    # --------------------------------------------------------

    - script: |
        echo "Installing Trivy..."

        sudo apt-get update

        sudo apt-get install -y wget apt-transport-https gnupg lsb-release

        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key \
          | gpg --dearmor \
          | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" \
          | sudo tee /etc/apt/sources.list.d/trivy.list

        sudo apt-get update
        sudo apt-get install -y trivy

        trivy fs \
          --scanners vuln,misconfig,secret \
          --severity HIGH,CRITICAL \
          --exit-code 0 \
          .
      displayName: Trivy Filesystem Scan

    # --------------------------------------------------------
    # Docker build
    # --------------------------------------------------------

    - script: |
        echo "Building Docker image..."

        docker build \
          -t employee-management:$(Build.BuildId) \
          .
      displayName: Build Docker Image

    # --------------------------------------------------------
    # Trivy Docker image scan
    # --------------------------------------------------------

    - script: |
        echo "Scanning Docker image..."

        trivy image \
          --severity HIGH,CRITICAL \
          --exit-code 0 \
          employee-management:$(Build.BuildId)
      displayName: Trivy Docker Image Scan

    # --------------------------------------------------------
    # PUSH TO AZURE CONTAINER REGISTRY
    # --------------------------------------------------------

    - task: AzureCLI@2
      displayName: Push Docker Image to ACR
      inputs:
        azureSubscription: azure-aks-wif
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          echo "Logging into Azure Container Registry..."

          az acr login \
            --name acrdevopsshiva2026

          echo "Tagging Docker image..."

          docker tag \
            employee-management:$(Build.BuildId) \
            acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)

          echo "Pushing image to ACR..."

          docker push \
            acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)

          echo "Image pushed successfully."

          echo "Image:"
          echo "acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)"


# ============================================================
# DEV
# ============================================================

- stage: DEV
  displayName: Deploy to DEV
  dependsOn: Build
  condition: succeeded()

  jobs:

  - deployment: DeployDEV
    displayName: Deploy Employee Management to AKS DEV
    environment: DEV

    strategy:
      runOnce:
        deploy:

          steps:

          - task: AzureCLI@2
            displayName: Deploy to AKS - DEV
            inputs:
              azureSubscription: azure-aks-wif
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                echo "Getting AKS credentials..."

                az aks get-credentials \
                  --resource-group rg-aks-devops-lab \
                  --name aks-devops-lab \
                  --overwrite-existing

                echo "Deploying Build $(Build.BuildId) to AKS..."

                kubectl set image \
                  deployment/employee-management \
                  employee-management=acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)

                echo "Waiting for rollout..."

                kubectl rollout status \
                  deployment/employee-management \
                  --timeout=180s

                echo "Deployment status:"

                kubectl get deployment employee-management

                echo "Pods:"

                kubectl get pods \
                  -l app=employee-management


# ============================================================
# QA
# ============================================================

- stage: QA
  displayName: Deploy to QA
  dependsOn: DEV
  condition: succeeded()

  jobs:

  - deployment: DeployQA
    displayName: Deploy Employee Management to AKS QA
    environment: QA

    strategy:
      runOnce:
        deploy:

          steps:

          - task: AzureCLI@2
            displayName: Deploy to AKS - QA
            inputs:
              azureSubscription: azure-aks-wif
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                echo "Getting AKS credentials..."

                az aks get-credentials \
                  --resource-group rg-aks-devops-lab \
                  --name aks-devops-lab \
                  --overwrite-existing

                echo "Deploying Build $(Build.BuildId) to AKS QA..."

                kubectl set image \
                  deployment/employee-management \
                  employee-management=acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)

                echo "Waiting for rollout..."

                kubectl rollout status \
                  deployment/employee-management \
                  --timeout=180s

                echo "Deployment status:"

                kubectl get deployment employee-management

                echo "Pods:"

                kubectl get pods \
                  -l app=employee-management


# ============================================================
# PROD
# ============================================================

- stage: PROD
  displayName: Deploy to PROD
  dependsOn: QA
  condition: succeeded()

  jobs:

  - deployment: DeployPROD
    displayName: Deploy Employee Management to AKS PROD

    # IMPORTANT:
    # Keep this environment.
    # Your PROD approval/check is attached to this environment.

    environment: PROD

    strategy:
      runOnce:
        deploy:

          steps:

          - task: AzureCLI@2
            displayName: Deploy to AKS - PROD
            inputs:
              azureSubscription: azure-aks-wif
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |

                echo "Getting AKS credentials..."

                az aks get-credentials \
                  --resource-group rg-aks-devops-lab \
                  --name aks-devops-lab \
                  --overwrite-existing

                echo "Deploying Build $(Build.BuildId) to AKS PROD..."

                kubectl set image \
                  deployment/employee-management \
                  employee-management=acrdevopsshiva2026.azurecr.io/employee-management:$(Build.BuildId)

                echo "Waiting for rollout..."

                kubectl rollout status \
                  deployment/employee-management \
                  --timeout=180s

                echo "Deployment status:"

                kubectl get deployment employee-management

                echo "Pods:"

                kubectl get pods \
                  -l app=employee-management
